export const types = [{
  key: 1,
  name: "Hot",
  api: "best",
  route: "",
  routeName: "index"
}, {
  key: 2,
  name: "New",
  api: "new",
  route: "new",
  routeName: "type"
}, {
  key: 3,
  name: "Top",
  api: "top",
  route: "top",
  routeName: "type"
}, {
  key: 4,
  name: "Controversial",
  api: "controversial",
  route: "controversial",
  routeName: "type"
}, {
  key: 5,
  name: "Rising",
  api: "rising",
  route: "rising",
  routeName: "type"
}]